name: PR Build & Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outcome }}
      lint-status: ${{ steps.lint.outcome }}

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run build
      - name: Build project
        id: build
        run: npm run build

      # Run lint
      - name: Run lint
        id: lint
        run: npm run lint || true   # prevent workflow from failing so we can report status

  comment-pr:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR with status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const buildOutcome = '${{ needs.build-and-test.outputs.build-status }}';
            const lintOutcome = '${{ needs.build-and-test.outputs.lint-status }}';
            const buildStatus = buildOutcome === 'success' ? '✅ Success' : '❌ Failed';
            const lintStatus = lintOutcome === 'success' ? '✅ Success' : '❌ Failed';
            const body = `
            | Check | Status |
            |-------|--------|
            | Build | ${buildStatus} |
            | Lint  | ${lintStatus} |
            `;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
